/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
        
        // Panel Interno
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        
        // Dimensiones del panel interno
        panelFormulario.setPreferredSize(new java.awt.Dimension(400, 380));
        
        // Layout nulo para usar coordenadas manuales (x, y, ancho, alto)
        panelFormulario.setLayout(null); 
        
        // setBounds(X, Y, Ancho, Alto). 
        lblRegistrarse.setBounds(70, 20, 280, 40);
        panelFormulario.add(lblRegistrarse);
        
        LblNombres.setBounds(50, 80, 100, 30);
        panelFormulario.add(LblNombres);

        txtNombres.setBounds(150, 80, 180, 30);
        panelFormulario.add(txtNombres);
        
        LblApellidos.setBounds(50, 130, 100, 30);
        panelFormulario.add(LblApellidos);
        
        txtApellidos.setBounds(150, 130, 180, 30);
        panelFormulario.add(txtApellidos);
        
        LblDni.setBounds(50, 180, 100, 30);
        panelFormulario.add(LblDni);
        
        txtDni.setBounds(150, 180, 180, 30);
        panelFormulario.add(txtDni);
        
        lblEmail.setBounds(50, 230, 100, 30);
        panelFormulario.add(lblEmail);
        
        txtEmail.setBounds(150, 230, 180, 30);
        panelFormulario.add(txtEmail);
        
        LblPassword.setBounds(50, 280, 100, 30);
        panelFormulario.add(LblPassword);
        
        txtPassword.setBounds(150, 280, 180, 30);
        panelFormulario.add(txtPassword);
        
        buttonVolver.setBounds(50, 330, 130, 30);
        panelFormulario.add(buttonVolver);
        
        buttonCreateAccount.setBounds(200, 330, 130, 30);
        panelFormulario.add(buttonCreateAccount);
        
        // GridBagLayout a PanelLogin principal
        this.setLayout(new java.awt.GridBagLayout());
        
        // Insertando todo ordenado al panel interno
        this.add(panelFormulario);
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblNombres = new javax.swing.JLabel();
        LblApellidos = new javax.swing.JLabel();
        LblDni = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        buttonCreateAccount = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRegistrarse = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        LblNombres.setText("Nombres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 89, 0, 0);
        add(LblNombres, gridBagConstraints);

        LblApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 89, 0, 0);
        add(LblApellidos, gridBagConstraints);

        LblDni.setText("DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 103, 0, 0);
        add(LblDni, gridBagConstraints);

        LblPassword.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 79, 0, 0);
        add(LblPassword, gridBagConstraints);

        txtNombres.addActionListener(this::txtNombresActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 68, 0, 0);
        add(txtNombres, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 68, 0, 0);
        add(txtApellidos, gridBagConstraints);

        txtDni.addActionListener(this::txtDniActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 68, 0, 0);
        add(txtDni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 68, 0, 0);
        add(txtPassword, gridBagConstraints);

        buttonCreateAccount.setText("Crear cuenta");
        buttonCreateAccount.addActionListener(this::buttonCreateAccountActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 54, 31, 92);
        add(buttonCreateAccount, gridBagConstraints);

        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(this::buttonVolverActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 79, 31, 0);
        add(buttonVolver, gridBagConstraints);

        lblEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 89, 0, 0);
        add(lblEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 68, 0, 0);
        add(txtEmail, gridBagConstraints);

        lblRegistrarse.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        lblRegistrarse.setText("Registrarse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 69, 0, 0);
        add(lblRegistrarse, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void buttonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCreateAccountActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    // --- GETTERS PARA EL CONTROLADOR ---
    public javax.swing.JTextField getTxtNombres() { return txtNombres; }
    public javax.swing.JTextField getTxtApellidos() { return txtApellidos; }
    public javax.swing.JTextField getTxtDni() { return txtDni; }
    public javax.swing.JTextField getTxtEmail() {return txtEmail; }
    public javax.swing.JPasswordField getTxtPassword() { return txtPassword; }
    public javax.swing.JButton getButtonCreateAccount() { return buttonCreateAccount; }
    public javax.swing.JButton getButtonVolver() { return buttonVolver; }
    
    // Método temporal por si aún no agregas el campo del código secreto para el Admin
    public String getCodigoAdmin() { return ""; }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblApellidos;
    private javax.swing.JLabel LblDni;
    private javax.swing.JLabel LblNombres;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
