/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelSistema
     */
    public PanelCliente() {
        initComponents();
        
        // 1. Limpiamos el panel principal
        this.removeAll();
        
        // 2. Panel Interno
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        
        // Dimensiones del panel interno (Ligeramente más ancho para el título)
        panelFormulario.setPreferredSize(new java.awt.Dimension(450, 350));
        
        // Layout nulo para usar coordenadas manuales (x, y, ancho, alto)
        panelFormulario.setLayout(null); 
        
        // 3. Acomodando los componentes con setBounds(X, Y, Ancho, Alto)
        
        // Título principal
        lblBienvenidoCliente.setBounds(20, 20, 410, 50);
        lblBienvenidoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); // Centra el texto
        panelFormulario.add(lblBienvenidoCliente);
        
        // Botones apilados y centrados (X = (450 - 200) / 2 = 125)
        buttonVerZonas.setBounds(125, 100, 200, 35);
        panelFormulario.add(buttonVerZonas);
        
        buttonComprarEntradas.setBounds(125, 150, 200, 35);
        panelFormulario.add(buttonComprarEntradas);
        
        buttonHistorialCompras.setBounds(125, 200, 200, 35);
        panelFormulario.add(buttonHistorialCompras);
        
        buttonCerrarSesion.setBounds(125, 250, 200, 35);
        panelFormulario.add(buttonCerrarSesion);

        // 4. GridBagLayout al panel principal para centrar la caja interior
        this.setLayout(new java.awt.GridBagLayout());
        this.add(panelFormulario);
        
        // 5. Refrescar la pantalla
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblBienvenidoCliente = new javax.swing.JLabel();
        buttonVerZonas = new javax.swing.JButton();
        buttonComprarEntradas = new javax.swing.JButton();
        buttonHistorialCompras = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblBienvenidoCliente.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        lblBienvenidoCliente.setText("¡Bienvenido!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 14, 0, 6);
        add(lblBienvenidoCliente, gridBagConstraints);

        buttonVerZonas.setText("Ver Zonas");
        buttonVerZonas.addActionListener(this::buttonVerZonasActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 229, 0, 0);
        add(buttonVerZonas, gridBagConstraints);

        buttonComprarEntradas.setText("Comprar Entradas");
        buttonComprarEntradas.addActionListener(this::buttonComprarEntradasActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 196, 0, 0);
        add(buttonComprarEntradas, gridBagConstraints);

        buttonHistorialCompras.setText("Historial de Compras");
        buttonHistorialCompras.addActionListener(this::buttonHistorialComprasActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 188, 0, 0);
        add(buttonHistorialCompras, gridBagConstraints);

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(this::buttonCerrarSesionActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 212, 43, 0);
        add(buttonCerrarSesion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHistorialComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHistorialComprasActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void buttonVerZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerZonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVerZonasActionPerformed

    private void buttonComprarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprarEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonComprarEntradasActionPerformed

    // --- GETTERS PARA EL FUTURO CONTROLADOR CLIENTE ---
    public javax.swing.JButton getButtonVerZonas() { return buttonVerZonas; }
    public javax.swing.JButton getButtonComprarEntradas() { return buttonComprarEntradas; }
    public javax.swing.JButton getButtonHistorialCompras() { return buttonHistorialCompras; }
    public javax.swing.JButton getButtonCerrarSesion() { return buttonCerrarSesion; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonComprarEntradas;
    private javax.swing.JButton buttonHistorialCompras;
    private javax.swing.JButton buttonVerZonas;
    private javax.swing.JLabel lblBienvenidoCliente;
    // End of variables declaration//GEN-END:variables
}
