/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelTarjetasRegistradas extends javax.swing.JPanel {

    /**
     * Creates new form PanelTarjetasRegistradas
     */
    public PanelTarjetasRegistradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarjetasRegistradas = new javax.swing.JTable();
        buttonVolver = new javax.swing.JButton();
        buttonEliminarTarjeta = new javax.swing.JButton();
        buttonAgregarTarjeta = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel1.setText("Tarjetas Registradas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 12, 0, 0);
        add(jLabel1, gridBagConstraints);

        jTableTarjetasRegistradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Nombre", "Fecha Venc.", "CVV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTarjetasRegistradas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 161;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 0, 42);
        add(jScrollPane1, gridBagConstraints);

        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(this::buttonVolverActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 43, 47, 0);
        add(buttonVolver, gridBagConstraints);

        buttonEliminarTarjeta.setText("EliminarTarjeta");
        buttonEliminarTarjeta.addActionListener(this::buttonEliminarTarjetaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 42, 47, 0);
        add(buttonEliminarTarjeta, gridBagConstraints);

        buttonAgregarTarjeta.setText("Agregar Tarjeta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 28, 47, 0);
        add(buttonAgregarTarjeta, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarTarjetaActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarTarjeta;
    private javax.swing.JButton buttonEliminarTarjeta;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarjetasRegistradas;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButtonAgregarTarjeta() { return buttonAgregarTarjeta; }
    public javax.swing.JButton getButtonEliminarTarjeta() { return buttonEliminarTarjeta; }
    public javax.swing.JButton getButtonVolver() { return buttonVolver; }
    
    public javax.swing.JTable getTablaTarjetas() {return jTableTarjetasRegistradas; }

    public void poblarTabla(modelo.Tarjeta[] listaTarjetas) {
        // 1. Capturamos el modelo de tu JTable (Reemplaza 'jTableTarjetas' por el nombre real de tu variable)
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableTarjetasRegistradas.getModel();
        
        // 2. Limpiamos las filas viejas para evitar que se dupliquen al entrar y salir del panel
        modelo.setRowCount(0);

        // 3. Recorremos el arreglo clásico [] y pintamos fila por fila
        for (int i = 0; i < listaTarjetas.length; i++) {
            modelo.Tarjeta t = listaTarjetas[i];
            
            // Enmascaramos el número por seguridad visual (Ej: "************3456")
            String numCompleto = t.getNumero();
            String numOculto = "************" + numCompleto.substring(numCompleto.length() - 4);

            Object[] fila = new Object[]{
                numOculto,       // Columna 0: Número oculto
                t.getNombre(),   // Columna 1: Titular
                t.getFecha(),    // Columna 2: Vencimiento
                "***"            // Columna 3: El CVV jamás se muestra por seguridad
            };
            
            modelo.addRow(fila);
        }
    }
}
