/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package vista;

/**
 *
 * @author leonel
 */
public class PanelLogin extends javax.swing.JPanel {

    /** Creates new form PanelLogin */
    /** Creates new form PanelLogin */
    public PanelLogin() {
        initComponents();
        this.removeAll();
        
        // Panel Interno
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        
        // Dimensiones del panel interno
        panelFormulario.setPreferredSize(new java.awt.Dimension(400, 350));
        
        // Layout nulo para usar coordenadas manuales (x, y, ancho, alto)
        panelFormulario.setLayout(null); 
        
        // setBounds(X, Y, Ancho, Alto). 
        LblIniciarSesion.setBounds(30, 20, 340, 40);
        panelFormulario.add(LblIniciarSesion);
        
        LbleEmail.setBounds(50, 100, 100, 30);
        panelFormulario.add(LbleEmail);
        
        txtEmail.setBounds(150, 100, 180, 30);
        panelFormulario.add(txtEmail);
        
        LblPassword.setBounds(50, 150, 100, 30);
        panelFormulario.add(LblPassword);
        
        txtPasswordField.setBounds(150, 150, 180, 30);
        panelFormulario.add(txtPasswordField);
        
        LblNoAccount.setBounds(55, 230, 200, 30);
        panelFormulario.add(LblNoAccount);
        
        buttonRegistrarse.setBounds(50, 260, 130, 30);
        panelFormulario.add(buttonRegistrarse);
        
        buttonLogin.setBounds(200, 260, 130, 30);
        panelFormulario.add(buttonLogin);

        // GridBagLayout a PanelLogin principal
        this.setLayout(new java.awt.GridBagLayout());
        
        // Insertando todo ordenado al panel interno
        this.add(panelFormulario);
        
        this.revalidate();
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LbleEmail = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        buttonRegistrarse = new javax.swing.JButton();
        LblNoAccount = new javax.swing.JLabel();
        txtPasswordField = new javax.swing.JPasswordField();
        LblIniciarSesion = new javax.swing.JLabel();

        setName(""); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        LbleEmail.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 92, 0, 0);
        add(LbleEmail, gridBagConstraints);

        LblPassword.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 80, 0, 0);
        add(LblPassword, gridBagConstraints);

        txtEmail.setColumns(10);
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 16, 0, 0);
        add(txtEmail, gridBagConstraints);

        buttonLogin.setText("Ingresar");
        buttonLogin.addActionListener(this::buttonLoginActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 42, 59, 0);
        add(buttonLogin, gridBagConstraints);

        buttonRegistrarse.setText("Registrarse");
        buttonRegistrarse.addActionListener(this::buttonRegistrarseActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 70, 59, 0);
        add(buttonRegistrarse, gridBagConstraints);

        LblNoAccount.setText("¿No tiene una cuenta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 48, 0, 0);
        add(LblNoAccount, gridBagConstraints);

        txtPasswordField.setColumns(10);
        txtPasswordField.addActionListener(this::txtPasswordFieldActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 0, 0);
        add(txtPasswordField, gridBagConstraints);

        LblIniciarSesion.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        LblIniciarSesion.setText("Iniciar Sesion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 48, 0, 55);
        add(LblIniciarSesion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarseActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblIniciarSesion;
    private javax.swing.JLabel LblNoAccount;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LbleEmail;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegistrarse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPasswordField;
    // End of variables declaration//GEN-END:variables
    
    
    // --- GETTERS PARA EL CONTROLADOR ---
    public javax.swing.JTextField getTxtEmail() { return txtEmail; }
    public javax.swing.JPasswordField getTxtPassword() { return txtPasswordField; }
    public javax.swing.JButton getButtonLogin() { return buttonLogin; }
    public javax.swing.JButton getButtonRegistrarse() { return buttonRegistrarse; }
}
