/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenidoAdmin = new javax.swing.JLabel();
        btnRegistrarConcierto = new javax.swing.JButton();
        buttonSupervisarVentas = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();

        lblBienvenidoAdmin.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        lblBienvenidoAdmin.setText("¡Bienvenido!");

        btnRegistrarConcierto.setText("Registrar Concierto");
        btnRegistrarConcierto.addActionListener(this::btnRegistrarConciertoActionPerformed);

        buttonSupervisarVentas.setText("Supervisar Ventas");
        buttonSupervisarVentas.addActionListener(this::buttonSupervisarVentasActionPerformed);

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(this::buttonCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenidoAdmin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSupervisarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarConcierto))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCerrarSesion)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblBienvenidoAdmin)
                .addGap(40, 40, 40)
                .addComponent(btnRegistrarConcierto)
                .addGap(28, 28, 28)
                .addComponent(buttonSupervisarVentas)
                .addGap(30, 30, 30)
                .addComponent(buttonCerrarSesion)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSupervisarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupervisarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSupervisarVentasActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void btnRegistrarConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConciertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarConciertoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarConcierto;
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonSupervisarVentas;
    private javax.swing.JLabel lblBienvenidoAdmin;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButtonRegistrarConcierto() { return btnRegistrarConcierto; }
    public javax.swing.JButton getButtonSupervisarVentas() { return buttonSupervisarVentas; }
    public javax.swing.JButton getButtonCerrarSesion() { return buttonCerrarSesion; }

}
