/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenidoAdmin = new javax.swing.JLabel();
        buttonGestionarZonas = new javax.swing.JButton();
        buttonSupervisarVentas = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();

        lblBienvenidoAdmin.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblBienvenidoAdmin.setText("¡Bienvenido, Administrador!");

        buttonGestionarZonas.setText("Gestionar Zonas");

        buttonSupervisarVentas.setText("Supervisar Ventas");
        buttonSupervisarVentas.addActionListener(this::buttonSupervisarVentasActionPerformed);

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(this::buttonCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonGestionarZonas)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenidoAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(buttonSupervisarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(buttonCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBienvenidoAdmin)
                .addGap(42, 42, 42)
                .addComponent(buttonGestionarZonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(buttonSupervisarVentas)
                .addGap(41, 41, 41)
                .addComponent(buttonCerrarSesion)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSupervisarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupervisarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSupervisarVentasActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonGestionarZonas;
    private javax.swing.JButton buttonSupervisarVentas;
    private javax.swing.JLabel lblBienvenidoAdmin;
    // End of variables declaration//GEN-END:variables
}
