/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelComprarEntradas extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprarEntradas
     */
    public PanelComprarEntradas() {
        initComponents();
        
        // 1. Limpiamos el diseño por defecto de NetBeans
        this.removeAll();
        
        // 2. Creamos la "caja" interna del formulario (Altura aumentada a 400)
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        panelFormulario.setPreferredSize(new java.awt.Dimension(450, 350));
        panelFormulario.setLayout(null); 
        
        // 3. Acomodamos los componentes con setBounds(X, Y, Ancho, Alto)
        
        // Título principal centrado
        lblTitulo.setBounds(25, 20, 400, 50);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFormulario.add(lblTitulo);
        
        // Fila 1: Zona
        lblZona.setBounds(70, 100, 150, 30);
        panelFormulario.add(lblZona);
        
        cboZonas.setBounds(220, 100, 160, 30);
        panelFormulario.add(cboZonas);
        
        // Fila 2: Cantidad de Entradas
        lblCantidadEntradas.setBounds(70, 150, 150, 30);
        panelFormulario.add(lblCantidadEntradas);
        
        cboCantidadEntradas.setBounds(220, 150, 160, 30);
        panelFormulario.add(cboCantidadEntradas);
        
        // Fila 3: Nro de Tarjeta
        lblNroTarjeta.setBounds(70, 200, 150, 30);
        panelFormulario.add(lblNroTarjeta);
        
        txtTarjeta.setBounds(220, 200, 160, 30);
        panelFormulario.add(txtTarjeta);
        
        // Fila 4: Botones Principales
        btnComprar.setBounds(70, 270, 140, 35);
        panelFormulario.add(btnComprar);
        
        btnVolver.setBounds(240, 270, 140, 35);
        panelFormulario.add(btnVolver);
        
        
        // 4. Centramos el formulario en el panel principal
        this.setLayout(new java.awt.GridBagLayout());
        this.add(panelFormulario);
        
        // 5. Refrescamos la pantalla
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZona = new javax.swing.JLabel();
        lblCantidadEntradas = new javax.swing.JLabel();
        cboZonas = new javax.swing.JComboBox<>();
        btnComprar = new javax.swing.JButton();
        lblNroTarjeta = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        cboCantidadEntradas = new javax.swing.JComboBox<>();

        lblZona.setText("Zona:");

        lblCantidadEntradas.setText("Cantidad de Entradas:");

        cboZonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platinum", "VIP", "General", "Tribuna" }));

        btnComprar.setText("Comprar");

        lblNroTarjeta.setText("Nro de Tarjeta:");

        lblTitulo.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        lblTitulo.setText("Comprar Entradas");

        btnVolver.setText("Volver");

        cboCantidadEntradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblZona)
                                .addGap(6, 6, 6)
                                .addComponent(cboZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidadEntradas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboCantidadEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolver)
                            .addComponent(lblNroTarjeta))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar)
                                .addGap(87, 87, 87))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblZona))
                    .addComponent(cboZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadEntradas)
                    .addComponent(cboCantidadEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNroTarjeta))
                    .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar)
                    .addComponent(btnVolver))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    // --- GETTERS PARA EL FUTURO CONTROLADOR CLIENTE ---
    public javax.swing.JComboBox<String> getCboZonas() { return cboZonas; }
    public javax.swing.JComboBox<String> getCboCantidadEntradas() { return cboCantidadEntradas; }
    public javax.swing.JTextField getTxtTarjeta() { return txtTarjeta; }
    public javax.swing.JButton getBtnComprar() { return btnComprar; }
    public javax.swing.JButton getBtnVolver() { return btnVolver; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboCantidadEntradas;
    public javax.swing.JComboBox<String> cboZonas;
    private javax.swing.JLabel lblCantidadEntradas;
    private javax.swing.JLabel lblNroTarjeta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblZona;
    public javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables

    public void prepararParaCompra(modelo.Concierto conciertoSeleccionado) {
        // 1. Cambiamos el título para que el cliente sepa qué está comprando
        lblTitulo.setText("Compra: " + conciertoSeleccionado.getNombre());

        // 2. Limpiamos las zonas estáticas y cargamos únicamente las zonas reales de este concierto
        cboZonas.removeAllItems();
        
        for (modelo.Zona z : conciertoSeleccionado.getZonas()) {
            cboZonas.addItem(z.getNombre());
        }
    }
}
