/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelRegistrarConcierto extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarConcierto
     */
    public PanelRegistrarConcierto() {
        initComponents();
        this.removeAll();
        
        // Panel Interno
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        
        // Dimensiones del panel interno
        panelFormulario.setPreferredSize(new java.awt.Dimension(500, 470));
        
        // Layout nulo para usar coordenadas manuales (x, y, ancho, alto)
        panelFormulario.setLayout(null); 
        
        lblTitulo.setBounds(100, 20, 300, 30);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFormulario.add(lblTitulo);
        
        lblNombreConcierto.setBounds(50, 70, 150, 30);
        panelFormulario.add(lblNombreConcierto);
        
        txtNombreConcierto.setBounds(230, 70, 200, 30);
        panelFormulario.add(txtNombreConcierto);
        
        lblFecha.setBounds(50, 120, 150, 30);
        panelFormulario.add(lblFecha);
        
        txtFechaConcierto.setBounds(230, 120, 200, 30);
        panelFormulario.add(txtFechaConcierto);
        
        lblTitulo2.setBounds(80, 170, 350, 30);
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFormulario.add(lblTitulo2);
        
        // Zona Platinum
        lblPlatinum.setBounds(50, 220, 80, 30);
        panelFormulario.add(lblPlatinum);
        
        lblCapacidadPlatinum.setBounds(140, 220, 80, 30);
        panelFormulario.add(lblCapacidadPlatinum);
        
        txtCapacidadPlatinum.setBounds(230, 220, 80, 30);
        panelFormulario.add(txtCapacidadPlatinum);
        
        lblPrecioPlatinum.setBounds(320, 220, 50, 30);
        panelFormulario.add(lblPrecioPlatinum);
        
        txtPrecioPlatinum.setBounds(380, 220, 80, 30);
        panelFormulario.add(txtPrecioPlatinum);
        
        // Zona VIP
        lblVip.setBounds(50, 270, 80, 30);
        panelFormulario.add(lblVip);
        
        lblCapacidadVip.setBounds(140, 270, 80, 30);
        panelFormulario.add(lblCapacidadVip);
        
        txtCapacidadVip.setBounds(230, 270, 80, 30);
        panelFormulario.add(txtCapacidadVip);
        
        lblPrecioVip.setBounds(320, 270, 50, 30);
        panelFormulario.add(lblPrecioVip);
        
        txtPrecioVip.setBounds(380, 270, 80, 30);
        panelFormulario.add(txtPrecioVip);
        
        //Zona General
        lblGeneral.setBounds(50, 320, 80, 30);
        panelFormulario.add(lblGeneral);
        
        lblCapacidadGeneral.setBounds(140, 320, 80, 30);
        panelFormulario.add(lblCapacidadGeneral);
        
        txtCapacidadGeneral.setBounds(230, 320, 80, 30);
        panelFormulario.add(txtCapacidadGeneral);
        
        lblPrecioGeneral.setBounds(320, 320, 50, 30);
        panelFormulario.add(lblPrecioGeneral);
        
        txtPrecioGeneral.setBounds(380, 320, 80, 30);
        panelFormulario.add(txtPrecioGeneral);
        
        // Zona Tribuna
        lblTribuna.setBounds(50, 370, 80, 30);
        panelFormulario.add(lblTribuna);
        
        lblCapacidadTribuna.setBounds(140, 370, 80, 30);
        panelFormulario.add(lblCapacidadTribuna);
        
        txtCapacidadTribuna.setBounds(230, 370, 80, 30);
        panelFormulario.add(txtCapacidadTribuna);
        
        lblPrecioTribuna.setBounds(320, 370, 50, 30);
        panelFormulario.add(lblPrecioTribuna);
        
        txtPrecioTribuna.setBounds(380, 370, 80, 30);
        panelFormulario.add(txtPrecioTribuna);
    
        buttonVolver.setBounds(140, 420, 100, 30);
        panelFormulario.add(buttonVolver);
    
        buttonRegistrarConcierto.setBounds(320, 420, 100, 30);
        panelFormulario.add(buttonRegistrarConcierto);
        
        this.setLayout(new java.awt.GridBagLayout());
        
        // Insertando todo ordenado al panel interno
        this.add(panelFormulario);
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitulo = new javax.swing.JLabel();
        lblNombreConcierto = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        buttonRegistrarConcierto = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        lblTitulo2 = new javax.swing.JLabel();
        lblPlatinum = new javax.swing.JLabel();
        lblVip = new javax.swing.JLabel();
        lblGeneral = new javax.swing.JLabel();
        lblTribuna = new javax.swing.JLabel();
        lblCapacidadPlatinum = new javax.swing.JLabel();
        lblCapacidadVip = new javax.swing.JLabel();
        lblCapacidadGeneral = new javax.swing.JLabel();
        lblCapacidadTribuna = new javax.swing.JLabel();
        txtNombreConcierto = new javax.swing.JTextField();
        txtFechaConcierto = new javax.swing.JTextField();
        lblPrecioPlatinum = new javax.swing.JLabel();
        lblPrecioVip = new javax.swing.JLabel();
        lblPrecioGeneral = new javax.swing.JLabel();
        lblPrecioTribuna = new javax.swing.JLabel();
        txtCapacidadPlatinum = new javax.swing.JTextField();
        txtCapacidadVip = new javax.swing.JTextField();
        txtCapacidadGeneral = new javax.swing.JTextField();
        txtCapacidadTribuna = new javax.swing.JTextField();
        txtPrecioPlatinum = new javax.swing.JTextField();
        txtPrecioVip = new javax.swing.JTextField();
        txtPrecioGeneral = new javax.swing.JTextField();
        txtPrecioTribuna = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Nimbus Mono PS", 3, 24)); // NOI18N
        lblTitulo.setText("Registrar Concierto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 13, 0, 0);
        add(lblTitulo, gridBagConstraints);

        lblNombreConcierto.setText("Nombre de Concierto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 69, 0, 0);
        add(lblNombreConcierto, gridBagConstraints);

        lblFecha.setText("Fecha dd/mm/yy :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 69, 0, 0);
        add(lblFecha, gridBagConstraints);

        buttonRegistrarConcierto.setText("Registrar ");
        buttonRegistrarConcierto.addActionListener(this::buttonRegistrarConciertoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 69, 35, 0);
        add(buttonRegistrarConcierto, gridBagConstraints);

        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(this::buttonVolverActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 16, 35, 0);
        add(buttonVolver, gridBagConstraints);

        lblTitulo2.setFont(new java.awt.Font("Nimbus Mono PS", 3, 24)); // NOI18N
        lblTitulo2.setText("Configuracion de Zonas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 99, 0, 0);
        add(lblTitulo2, gridBagConstraints);

        lblPlatinum.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblPlatinum.setText("Platinum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 69, 0, 0);
        add(lblPlatinum, gridBagConstraints);

        lblVip.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblVip.setText("VIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 88, 0, 0);
        add(lblVip, gridBagConstraints);

        lblGeneral.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblGeneral.setText("General");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 69, 0, 0);
        add(lblGeneral, gridBagConstraints);

        lblTribuna.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTribuna.setText("Tribuna");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 69, 0, 0);
        add(lblTribuna, gridBagConstraints);

        lblCapacidadPlatinum.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblCapacidadPlatinum, gridBagConstraints);

        lblCapacidadVip.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblCapacidadVip, gridBagConstraints);

        lblCapacidadGeneral.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblCapacidadGeneral, gridBagConstraints);

        lblCapacidadTribuna.setText("Capacidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblCapacidadTribuna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 37);
        add(txtNombreConcierto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 37);
        add(txtFechaConcierto, gridBagConstraints);

        lblPrecioPlatinum.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblPrecioPlatinum, gridBagConstraints);

        lblPrecioVip.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblPrecioVip, gridBagConstraints);

        lblPrecioGeneral.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblPrecioGeneral, gridBagConstraints);

        lblPrecioTribuna.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(lblPrecioTribuna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtCapacidadPlatinum, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtCapacidadVip, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtCapacidadGeneral, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtCapacidadTribuna, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtPrecioPlatinum, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtPrecioVip, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtPrecioGeneral, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        add(txtPrecioTribuna, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarConciertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarConciertoActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrarConcierto;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel lblCapacidadGeneral;
    private javax.swing.JLabel lblCapacidadPlatinum;
    private javax.swing.JLabel lblCapacidadTribuna;
    private javax.swing.JLabel lblCapacidadVip;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGeneral;
    private javax.swing.JLabel lblNombreConcierto;
    private javax.swing.JLabel lblPlatinum;
    private javax.swing.JLabel lblPrecioGeneral;
    private javax.swing.JLabel lblPrecioPlatinum;
    private javax.swing.JLabel lblPrecioTribuna;
    private javax.swing.JLabel lblPrecioVip;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTribuna;
    private javax.swing.JLabel lblVip;
    private javax.swing.JTextField txtCapacidadGeneral;
    private javax.swing.JTextField txtCapacidadPlatinum;
    private javax.swing.JTextField txtCapacidadTribuna;
    private javax.swing.JTextField txtCapacidadVip;
    private javax.swing.JTextField txtFechaConcierto;
    private javax.swing.JTextField txtNombreConcierto;
    private javax.swing.JTextField txtPrecioGeneral;
    private javax.swing.JTextField txtPrecioPlatinum;
    private javax.swing.JTextField txtPrecioTribuna;
    private javax.swing.JTextField txtPrecioVip;
    // End of variables declaration//GEN-END:variables

    //Getters

    // TextFields principales
    public javax.swing.JTextField getTxtNombreConcierto() { return txtNombreConcierto; }
    public javax.swing.JTextField getTxtFechaConcierto() { return txtFechaConcierto; }

    // TextFields de Capacidades
    public javax.swing.JTextField getTxtCapacidadPlatinum() { return txtCapacidadPlatinum; }
    public javax.swing.JTextField getTxtCapacidadVip() { return txtCapacidadVip; }
    public javax.swing.JTextField getTxtCapacidadGeneral() { return txtCapacidadGeneral; }
    public javax.swing.JTextField getTxtCapacidadTribuna() { return txtCapacidadTribuna; }

    // TextFields de Precios
    public javax.swing.JTextField getTxtPrecioPlatinum() { return txtPrecioPlatinum; }
    public javax.swing.JTextField getTxtPrecioVip() { return txtPrecioVip; }
    public javax.swing.JTextField getTxtPrecioGeneral() { return txtPrecioGeneral; }
    public javax.swing.JTextField getTxtPrecioTribuna() { return txtPrecioTribuna; }

    // Botones
    public javax.swing.JButton getButtonRegistrarConcierto() { return buttonRegistrarConcierto; }
    public javax.swing.JButton getButtonVolver() { return buttonVolver; }

}
