/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelComprarEntradas extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprarEntradas
     */
    public PanelComprarEntradas() {
        initComponents();
        
        // 1. Limpiamos el diseño por defecto de NetBeans
        this.removeAll();
        
        // 2. Creamos la "caja" interna del formulario (Altura aumentada a 400)
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel();
        panelFormulario.setPreferredSize(new java.awt.Dimension(450, 400));
        panelFormulario.setLayout(null); 
        
        // 3. Acomodamos los componentes con setBounds(X, Y, Ancho, Alto)
        
        // Título principal centrado
        lblTitulo.setBounds(25, 20, 400, 50);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFormulario.add(lblTitulo);
        
        // Fila 1: Zona
        lblZona.setBounds(70, 100, 150, 30);
        panelFormulario.add(lblZona);
        
        cboZonas.setBounds(220, 100, 160, 30);
        panelFormulario.add(cboZonas);
        
        // Fila 2: Cantidad de Entradas
        lblCantidadEntradas.setBounds(70, 150, 150, 30);
        panelFormulario.add(lblCantidadEntradas);
        
        txtCantidad.setBounds(220, 150, 160, 30);
        panelFormulario.add(txtCantidad);
        
        // Fila 3: Nro de Tarjeta
        lblNroTarjeta.setBounds(70, 200, 150, 30);
        panelFormulario.add(lblNroTarjeta);
        
        txtTarjeta.setBounds(220, 200, 160, 30);
        panelFormulario.add(txtTarjeta);
        
        // Fila 4: Botones Principales
        btnComprar.setBounds(70, 270, 140, 35);
        panelFormulario.add(btnComprar);
        
        btnEstadisticas.setBounds(240, 270, 140, 35);
        panelFormulario.add(btnEstadisticas);
        
        // Fila 5: Botón Volver (Centrado debajo de los anteriores)
        btnVolver.setBounds(155, 325, 140, 35);
        panelFormulario.add(btnVolver);
        
        // 4. Centramos el formulario en el panel principal
        this.setLayout(new java.awt.GridBagLayout());
        this.add(panelFormulario);
        
        // 5. Refrescamos la pantalla
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblZona = new javax.swing.JLabel();
        lblCantidadEntradas = new javax.swing.JLabel();
        cboZonas = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        lblNroTarjeta = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        btnEstadisticas = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblZona.setText("Zona:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 61, 0, 0);
        add(lblZona, gridBagConstraints);

        lblCantidadEntradas.setText("Cantidad de Entradas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 61, 0, 0);
        add(lblCantidadEntradas, gridBagConstraints);

        cboZonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 6, 0, 0);
        add(cboZonas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(txtCantidad, gridBagConstraints);

        btnComprar.setText("Comprar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 61, 55, 0);
        add(btnComprar, gridBagConstraints);

        lblNroTarjeta.setText("Nro de Tarjeta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 61, 0, 0);
        add(lblNroTarjeta, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(txtTarjeta, gridBagConstraints);

        btnEstadisticas.setText("Ver Estadísticas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 23, 55, 0);
        add(btnEstadisticas, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Nimbus Mono PS", 0, 36)); // NOI18N
        lblTitulo.setText("Comprar Entradas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 34, 0, 27);
        add(lblTitulo, gridBagConstraints);

        btnVolver.setText("Volver");
        add(btnVolver, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    // --- GETTERS PARA EL FUTURO CONTROLADOR CLIENTE ---
    public javax.swing.JComboBox<String> getCboZonas() { return cboZonas; }
    public javax.swing.JTextField getTxtCantidad() { return txtCantidad; }
    public javax.swing.JTextField getTxtTarjeta() { return txtTarjeta; }
    public javax.swing.JButton getBtnComprar() { return btnComprar; }
    public javax.swing.JButton getBtnEstadisticas() { return btnEstadisticas; }
    public javax.swing.JButton getBtnVolver() { return btnVolver; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComprar;
    public javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cboZonas;
    private javax.swing.JLabel lblCantidadEntradas;
    private javax.swing.JLabel lblNroTarjeta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblZona;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}
