/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelAgregarTarjeta extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarTarjeta
     */
    public PanelAgregarTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNumeroTarjeta = new javax.swing.JLabel();
        lblNombreTitular = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        lblCvv = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        txtNombreTitular = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        buttonVolver = new javax.swing.JButton();
        buttonGuardarTarjeta = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lblTitulo.setText("Agregar Tarjeta");

        lblNumeroTarjeta.setText("Numero de Tarjeta:");

        lblNombreTitular.setText("Nombre del Titular:");

        lblFechaVencimiento.setText("Fecha de Vencimiento:");

        lblCvv.setText("CVV:");

        buttonVolver.setText("Volver");

        buttonGuardarTarjeta.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroTarjeta)
                    .addComponent(lblNombreTitular)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(lblCvv)
                    .addComponent(buttonVolver, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreTitular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCvv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(buttonGuardarTarjeta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroTarjeta)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTitular)
                    .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCvv)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVolver)
                    .addComponent(buttonGuardarTarjeta))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGuardarTarjeta;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblNombreTitular;
    private javax.swing.JLabel lblNumeroTarjeta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreTitular;
    private javax.swing.JTextField txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtNumeroTarjeta() { return txtNumeroTarjeta; }
    public javax.swing.JTextField getTxtNombreTitular() { return txtNombreTitular; }
    public javax.swing.JTextField getTxtFechaVencimiento() { return txtFechaVencimiento; }
    public javax.swing.JTextField getTxtCvv() { return txtCvv; }
    
    public javax.swing.JButton getButtonVolver() { return buttonVolver; }
    public javax.swing.JButton getButtonGuardarTarjeta() { return buttonGuardarTarjeta; }
}
