/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class PanelCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelSistema
     */
    public PanelCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenidoCliente = new javax.swing.JLabel();
        buttonVerZonas = new javax.swing.JButton();
        buttonComprarEntradas = new javax.swing.JButton();
        buttonHistorialCompras = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();

        lblBienvenidoCliente.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblBienvenidoCliente.setText("¡Bienvenido al Sistema!");

        buttonVerZonas.setText("Ver Zonas");

        buttonComprarEntradas.setText("Comprar Entradas");

        buttonHistorialCompras.setText("Historial de Compras");
        buttonHistorialCompras.addActionListener(this::buttonHistorialComprasActionPerformed);

        buttonCerrarSesion.setText("Cerrar Sesion");
        buttonCerrarSesion.addActionListener(this::buttonCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblBienvenidoCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonHistorialCompras)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonComprarEntradas)
                                .addGap(8, 8, 8)))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVerZonas)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCerrarSesion)
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBienvenidoCliente)
                .addGap(29, 29, 29)
                .addComponent(buttonVerZonas)
                .addGap(27, 27, 27)
                .addComponent(buttonComprarEntradas)
                .addGap(27, 27, 27)
                .addComponent(buttonHistorialCompras)
                .addGap(26, 26, 26)
                .addComponent(buttonCerrarSesion)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHistorialComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHistorialComprasActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonComprarEntradas;
    private javax.swing.JButton buttonHistorialCompras;
    private javax.swing.JButton buttonVerZonas;
    private javax.swing.JLabel lblBienvenidoCliente;
    // End of variables declaration//GEN-END:variables
}
