/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author leonel
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
        // Tamaño fijo ventana
        this.setSize(600, 500);
        
        this.setLocationRelativeTo(null);
        
        // Instancias de paneles
        PanelLogin panelLogin = new PanelLogin();
        PanelRegistro panelRegistro = new PanelRegistro();
        PanelCliente panelCliente = new PanelCliente();
        PanelAdmin panelAdmin = new PanelAdmin();
        PanelComprarEntradas panelComprarEntradas = new PanelComprarEntradas();
        PanelConciertosDisponibles panelConciertosDisponibles = new PanelConciertosDisponibles();
        PanelRegistrarConcierto panelRegistrarConcierto = new PanelRegistrarConcierto();
        PanelSupervisarVentas panelSupervisarVentas = new PanelSupervisarVentas();
        PanelGestionZonas panelGestionZonas = new PanelGestionZonas();
        PanelHistorialCompras panelHistorialCompras = new PanelHistorialCompras();
        PanelTarjetasRegistradas panelTarjetasRegistradas = new PanelTarjetasRegistradas();
        PanelAgregarTarjeta panelAgregarTarjeta = new PanelAgregarTarjeta();
        
        
        // Card names
        jPanel1.add(panelLogin, "login");
        jPanel1.add(panelRegistro, "registro");
        jPanel1.add(panelCliente, "cliente");
        jPanel1.add(panelAdmin, "admin");
        jPanel1.add(panelComprarEntradas, "comprarEntradas");
        jPanel1.add(panelConciertosDisponibles, "conciertosDisponibles");
        jPanel1.add(panelRegistrarConcierto, "registrarConcierto");
        jPanel1.add(panelSupervisarVentas, "supervisarVentas");
        jPanel1.add(panelGestionZonas, "gestionZonas");
        jPanel1.add(panelHistorialCompras, "historialCompras");
        jPanel1.add(panelTarjetasRegistradas, "tarjetasRegistradas");
        jPanel1.add(panelAgregarTarjeta, "agregarTarjeta");
        
        controlador.ControladorRegistrarConcierto controlRegistrarConcierto = new controlador.ControladorRegistrarConcierto(
            panelRegistrarConcierto, 
            jPanel1
        );
        
        controlador.ControladorTarjetasRegistradas controlTarjetasRegistradas = new controlador.ControladorTarjetasRegistradas(
            panelTarjetasRegistradas,
            jPanel1
        );
        
        controlador.ControladorAgregarTarjeta controlAgregarTarjeta = new controlador.ControladorAgregarTarjeta(
            panelAgregarTarjeta,    
            jPanel1,
            controlTarjetasRegistradas    
        );
        
        controlador.ControladorComprarEntradas controlComprarEntradas = new controlador.ControladorComprarEntradas(
            panelComprarEntradas,
            jPanel1
        );
        
        controlador.ControladorConciertosDisponibles controlConciertosDisponibles = new controlador.ControladorConciertosDisponibles(
            panelConciertosDisponibles, 
            jPanel1,
            controlComprarEntradas
        );
        
        controlador.ControladorCliente cCliente = new controlador.ControladorCliente(
            panelCliente, 
            jPanel1,
            controlConciertosDisponibles,
            controlTarjetasRegistradas,
            controlAgregarTarjeta
        );
        
        controlador.ControladorSupervisarVentas controlSupervisarVentas = new controlador.ControladorSupervisarVentas(
            panelSupervisarVentas,
            jPanel1
        );

        controlador.ControladorGestionZonas controlGestionZonas = new controlador.ControladorGestionZonas(
            panelGestionZonas,
            jPanel1
        );

        controlador.ControladorAdmin cAdmin = new controlador.ControladorAdmin(
            panelAdmin,
            jPanel1,
            controlSupervisarVentas,
            controlGestionZonas
        );
        
        controlador.ControladorLogin controlLogin = new controlador.ControladorLogin(
            panelLogin, 
            jPanel1,
            cCliente,
            cAdmin
        );
        
        controlador.ControladorRegistro controlRegistro = new controlador.ControladorRegistro(
            panelRegistro,
            jPanel1,
            cCliente
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
